// <auto-generated />
using System;
using Goalsetter.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Goalsetter.DataAccess.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Goalsetter.Domains.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VehicleID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Makes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9b113ec-d702-46cb-a4fe-175dfb446171"),
                            CreatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 995, DateTimeKind.Utc).AddTicks(2395),
                            IsActive = true,
                            Makes = "Chevrolet",
                            Model = "Cruze",
                            UpdatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 995, DateTimeKind.Utc).AddTicks(2395),
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("d29bd38f-9dfb-4e99-9388-e9c097649d0b"),
                            CreatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 996, DateTimeKind.Utc).AddTicks(5291),
                            IsActive = true,
                            Makes = "Chevrolet",
                            Model = "Corsa",
                            UpdatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 996, DateTimeKind.Utc).AddTicks(5291),
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("7ebed128-896e-4f05-a43d-6ee7c78d29a8"),
                            CreatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 996, DateTimeKind.Utc).AddTicks(5310),
                            IsActive = true,
                            Makes = "Ford",
                            Model = "F-100",
                            UpdatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 996, DateTimeKind.Utc).AddTicks(5310),
                            Year = 2000
                        },
                        new
                        {
                            Id = new Guid("e4130ceb-7482-4858-86d2-a61f517037eb"),
                            CreatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 996, DateTimeKind.Utc).AddTicks(5314),
                            IsActive = true,
                            Makes = "Fiat",
                            Model = "Palio",
                            UpdatedDate = new DateTime(2020, 11, 27, 0, 18, 28, 996, DateTimeKind.Utc).AddTicks(5314),
                            Year = 2008
                        });
                });

            modelBuilder.Entity("Goalsetter.Domains.VehiclePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VehiclePrice");
                });
#pragma warning restore 612, 618
        }
    }
}
